/**
 * Auto Generated by LibragonExporter for TexturePacker
 **/

#include <libdragon.h>
#include <malloc.h>

typedef enum _{{texture.trimmedName}}_sprites { {% for sprite in allSprites %}
    SPRITE_{{sprite.trimmedName}},{% endfor %}
    SPRITE_{{texture.trimmedName}}_SPRITES_MAX
} {{texture.trimmedName}}_sprites;

#define alloc_and_load_spritesheet_{{texture.trimmedName}}(sprite)\
{\
    int fp = dfs_open("/{{texture.trimmedName}}.sprite");\
    sprite = (sprite_t*)malloc(dfs_size(fp));\
    dfs_read(sprite, 1, dfs_size(fp), fp);\
    dfs_close(fp);\
}
