/**
 * Auto Generated by LibragonExporter for TexturePacker
 **/

#include <libdragon.h>
#include <malloc.h>

typedef enum _{{texture.trimmedName}} { {% for sprite in allSprites %}
    {{sprite.trimmedName}}{% if not forloop.last %},{% endif %}{% endfor %}
} {{texture.trimmedName}};

void alloc_and_load_spritesheet_{{texture.trimmedName}}(sprite_t* sprite) {
    int fp = dfs_open("/{{texture.trimmedName}}.sprite");
    sprite = malloc(dfs_size(fp));
    dfs_read(sprite, 1, dfs_size(fp), fp);
    dfs_close(fp);
}
